export class InputParams {
  label?: string;
  type?: string;
  name?: string;
  value?: string;
  onChange?: (e: any) => void;
  placeholder?: string;
  className?: string;
  required?: boolean;
  disabled?: boolean;
  readOnly?: boolean;
  autoFocus?: boolean;
  autoComplete?: string;
  min?: number;
  max?: number;
  step?: number;
  pattern?: string;
  title?: string;
  maxLength?: number;
  minLength?: number;
  size?: number;
  height?: number;
  width?: number;
  rows?: number;
  cols?: number;
  checked?: boolean;
  multiple?: boolean;
  accept?: string;
  form?: string;
  formAction?: string;
  formEncType?: string;
  formMethod?: string;
  formNoValidate?: boolean;
  formTarget?: string;
  list?: string;
  src?: string;
  onClick?: (e: any) => void;
  onDoubleClick?: (e: any) => void;
  onDrag?: (e: any) => void;
  onDragEnd?: (e: any) => void;
  onDragEnter?: (e: any) => void;
  onDragExit?: (e: any) => void;
  onDragLeave?: (e: any) => void;
  onDragOver?: (e: any) => void;
  onDragStart?: (e: any) => void;
  onDrop?: (e: any) => void;
  onMouseDown?: (e: any) => void;
  onMouseEnter?: (e: any) => void;
  onMouseLeave?: (e: any) => void;
  onMouseMove?: (e: any) => void;
  onMouseOut?: (e: any) => void;
}
